[sharding]
low = 1
high = 8

[csBasic]
numUsers = 10000
boundaryProb = 0.1
numLookups = 400
queries = ["full_ohua"]

[[csBasic.eventRange]]
low = 1000
high = 1300

[[csBasic.eventRange]]
low = 1300
high = 1600

[[csBasic.eventRange]]
low = 1600
high = 1900

[[csBasic.eventRange]]
low = 2200
high = 2600
