[workspace]
members = [
	"noria",
	"noria-server",
	"noria-benchmarks",
	"noria-benchmarks/lobsters",
]

[profile.release]
debug=true

[replace]
'nom-sql:0.0.6' = { git = " https://github.com/JustusAdam/nom-sql", branch = "udfs" }