numUsers = 4000
boundaryProb = 0.1
numLookups = 100
queries = ["pure_sql"] # "manual", "partial_ohua", "full_ohua"]

[[eventRange]]
low = 100
high = 150

# [[eventRange]]
# low = 200
# high = 300

# [[eventRange]]
# low = 400
# high = 600

# [[eventRange]]
# low = 500
# high = 700

# [[eventRange]]
# low = 600
# high = 900

# [[eventRange]]
# low = 700
# high = 1000