
numSelectable = 8000
lookupRounds = 10
lookupsPerRound = 20
queries = ["sql", "ohua"]

[valueLimit]
low = -10000
high = 10000

[[numGenRange]]
low = 0
high = 60

[[numGenRange]]
low = 50
high = 100

[[numGenRange]]
low = 100
high = 150

[[numGenRange]]
low = 150
high = 200

[[numGenRange]]
low = 200
high = 250

[[numGenRange]]
low = 250
high = 300

[[numGenRange]]
low = 300
high = 350

[[numGenRange]]
low = 350
high = 400

[[numGenRange]]
low = 400
high = 450